//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetWebApplication.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnosG5
    {
        public int PersonIdG5 { get; set; }
        public string Carnet { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Sede { get; set; }
        public string Plan { get; set; }
        public string Centro_educativo { get; set; }
    }
}
